# Input/Output

Often, it is important to import information from a variety of sources and output the result. Here, we demonstrate a few ways of creating and saving files.

By the end of this file you should have seen simple examples of:
1. Printing string output to the screen
2. Reading and writing string output to/from text files
3. Reading and writing string output to/from csv files
4. Reading and writing string output to/from binary files
5. Reading and writing string output to/from matlab files

In [5]:
#Python Imports:
import numpy as np
import scipy.io as sio
%cd datafiles

[WinError 2] The system cannot find the file specified: 'datafiles'
C:\Users\bfleischer3\Dropbox\PACE\Projects\Courses\Intro to Scientific Python\datafiles


## From standard input/keyboard:
The import of simple text files can be performed directly in python via: 

In [6]:
kb_contents = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
print(kb_contents)

Lorem ipsum dolor sit amet, consectetur adipiscing elit.


## Text (ascii) files:
The import of simple text files can be performed directly in python by creating a file object and operating on that object:

In [7]:
#Read line by line:
file_obj = open('01-simpletext.txt','r')
for line in file_obj:
    print(line)
file_obj.close()

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam leo purus, interdum sed interdum quis, tincidunt ac nibh. 



Maecenas a purus massa. Nunc a augue augue. Donec in felis commodo lectus convallis elementum sed vitae ipsum.


In [8]:
#Use the read method:
file_obj = open('01-simpletext.txt','r')
file_contents = file_obj.read()
file_obj.close()
print(file_contents)

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam leo purus, interdum sed interdum quis, tincidunt ac nibh. 

Maecenas a purus massa. Nunc a augue augue. Donec in felis commodo lectus convallis elementum sed vitae ipsum.


In [9]:
#Python 'with' statement automatically takes care of the close for us:
with open('01-simpletext.txt','r') as file_obj:
    print(file_obj.read())

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam leo purus, interdum sed interdum quis, tincidunt ac nibh. 

Maecenas a purus massa. Nunc a augue augue. Donec in felis commodo lectus convallis elementum sed vitae ipsum.


In [10]:
# Write to ascii files:
file_obj = open('01-simpletext_write.txt','w')
file_obj.write(file_contents)
file_obj.close()

# Or, alternatively:
with open('01-simpletext_write.txt','w') as file_obj:
    file_obj.write(file_contents)

# Check that our written output is good:
with open('01-simpletext_write.txt','r') as file_obj:
    print(file_obj.read())

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam leo purus, interdum sed interdum quis, tincidunt ac nibh. 

Maecenas a purus massa. Nunc a augue augue. Donec in felis commodo lectus convallis elementum sed vitae ipsum.


## Comma Separated Values
Here, we import data separated by a particular delimiter, as in tsv or csv files:

In [11]:
#Creating a python list:
file_obj = open('01-simpledata.csv','r')
file_contents = file_obj.read().split(',')
file_obj.close()
print(file_contents)

['1', '0.012', '2', '0.024\n2', '0.014', '4', '0.056\n3', '0.016', '8', '0.128\n4', '0.018', '16', '0.288\n5', '0.020', '32', '0.640\n6', '0.022', '64', '1.408\n7', '0.024', '128', '3.072\n8', '0.026', '256', '6.656\n9', '0.028', '512', '14.336\n10', '0.030', '1024', '30.720']


In [12]:
#Use numpy to read an array from a file
file_contents = np.loadtxt(open('01-simpledata.csv'), delimiter=",")
file_contents = file_contents.astype('float')
print(file_contents)

[[  1.00000000e+00   1.20000000e-02   2.00000000e+00   2.40000000e-02]
 [  2.00000000e+00   1.40000000e-02   4.00000000e+00   5.60000000e-02]
 [  3.00000000e+00   1.60000000e-02   8.00000000e+00   1.28000000e-01]
 [  4.00000000e+00   1.80000000e-02   1.60000000e+01   2.88000000e-01]
 [  5.00000000e+00   2.00000000e-02   3.20000000e+01   6.40000000e-01]
 [  6.00000000e+00   2.20000000e-02   6.40000000e+01   1.40800000e+00]
 [  7.00000000e+00   2.40000000e-02   1.28000000e+02   3.07200000e+00]
 [  8.00000000e+00   2.60000000e-02   2.56000000e+02   6.65600000e+00]
 [  9.00000000e+00   2.80000000e-02   5.12000000e+02   1.43360000e+01]
 [  1.00000000e+01   3.00000000e-02   1.02400000e+03   3.07200000e+01]]


In [13]:
#Save output of numpy array to csv file
file_contents_write = file_contents*2 #Double to differentiate read vs write data

np.savetxt('01-simpledata_write.csv',file_contents_write, '%0.3f', delimiter=",") 
# %0.3f specifices 3 decimal places
file_contents = np.loadtxt(open('01-simpledata_write.csv'), delimiter=",")
print(file_contents)

[[  2.00000000e+00   2.40000000e-02   4.00000000e+00   4.80000000e-02]
 [  4.00000000e+00   2.80000000e-02   8.00000000e+00   1.12000000e-01]
 [  6.00000000e+00   3.20000000e-02   1.60000000e+01   2.56000000e-01]
 [  8.00000000e+00   3.60000000e-02   3.20000000e+01   5.76000000e-01]
 [  1.00000000e+01   4.00000000e-02   6.40000000e+01   1.28000000e+00]
 [  1.20000000e+01   4.40000000e-02   1.28000000e+02   2.81600000e+00]
 [  1.40000000e+01   4.80000000e-02   2.56000000e+02   6.14400000e+00]
 [  1.60000000e+01   5.20000000e-02   5.12000000e+02   1.33120000e+01]
 [  1.80000000e+01   5.60000000e-02   1.02400000e+03   2.86720000e+01]
 [  2.00000000e+01   6.00000000e-02   2.04800000e+03   6.14400000e+01]]


## Read from Binary File
Binary files store the same information as text or csv, but do so directly in bytes, rather than using ascii to encode. They have the advantage of being faster to read and smaller in size, but are not readily readable by a typical text editor (notepad, vim, sublime, etc).

Note: be careful to avoid `numpy.fromfile` and `numpy.tofile` as they are not platform independent!

In [30]:
# Read in the csv from the previous step:
file_contents = np.loadtxt(open('01-simpledata_write.csv'), delimiter=",")
print(file_contents)

[[  2.00000000e+00   2.40000000e-02   4.00000000e+00   4.80000000e-02]
 [  4.00000000e+00   2.80000000e-02   8.00000000e+00   1.12000000e-01]
 [  6.00000000e+00   3.20000000e-02   1.60000000e+01   2.56000000e-01]
 [  8.00000000e+00   3.60000000e-02   3.20000000e+01   5.76000000e-01]
 [  1.00000000e+01   4.00000000e-02   6.40000000e+01   1.28000000e+00]
 [  1.20000000e+01   4.40000000e-02   1.28000000e+02   2.81600000e+00]
 [  1.40000000e+01   4.80000000e-02   2.56000000e+02   6.14400000e+00]
 [  1.60000000e+01   5.20000000e-02   5.12000000e+02   1.33120000e+01]
 [  1.80000000e+01   5.60000000e-02   1.02400000e+03   2.86720000e+01]
 [  2.00000000e+01   6.00000000e-02   2.04800000e+03   6.14400000e+01]]


In [43]:
# Save as a binary file:
np.savetxt('01-simpledata_write.bin', file_contents_write*2) # Note the lack of demiliter
file_contents = np.loadtxt('01-simpledata_write.bin')

# The following is not recommended, as it is platform dependent:
#np.ndarray.tofile(file_contents_write, '01-simpledata_write.bin')
#file_contents = np.fromfile('01-simpledata_write.bin')

print(file_contents)

[  4.00000000e+00   4.80000000e-02   8.00000000e+00   9.60000000e-02
   8.00000000e+00   5.60000000e-02   1.60000000e+01   2.24000000e-01
   1.20000000e+01   6.40000000e-02   3.20000000e+01   5.12000000e-01
   1.60000000e+01   7.20000000e-02   6.40000000e+01   1.15200000e+00
   2.00000000e+01   8.00000000e-02   1.28000000e+02   2.56000000e+00
   2.40000000e+01   8.80000000e-02   2.56000000e+02   5.63200000e+00
   2.80000000e+01   9.60000000e-02   5.12000000e+02   1.22880000e+01
   3.20000000e+01   1.04000000e-01   1.02400000e+03   2.66240000e+01
   3.60000000e+01   1.12000000e-01   2.04800000e+03   5.73440000e+01
   4.00000000e+01   1.20000000e-01   4.09600000e+03   1.22880000e+02]


## Matlab .mat files
Generating matlab variables via:

``testvar = magic(9)``

``save('01-simplemat.mat','testvar')``

These can then be loaded via scipy.io (imported as sio here):

In [22]:
# Use scipy to read in .mat files:
mat_contents= sio.loadmat('01-simplemat.mat')

testvar = mat_contents['testvar']
print(testvar)

[[47 58 69 80  1 12 23 34 45]
 [57 68 79  9 11 22 33 44 46]
 [67 78  8 10 21 32 43 54 56]
 [77  7 18 20 31 42 53 55 66]
 [ 6 17 19 30 41 52 63 65 76]
 [16 27 29 40 51 62 64 75  5]
 [26 28 39 50 61 72 74  4 15]
 [36 38 49 60 71 73  3 14 25]
 [37 48 59 70 81  2 13 24 35]]


In [21]:
# Use scipy to write .mat files:
testvar_write = testvar*2 # Double to make read data different from write data

sio.savemat('01-simplemat_write.mat' ,{'testvar_write':testvar_write})

mat_contents = sio.loadmat('01-simplemat_write.mat')
testvar = mat_contents['testvar_write']
print(testvar_write)

[[188 232  20  64   4  48  92 136 180]
 [228  16  60  36  44  88 132 176 184]
 [ 12  56  32  40  84 128 172 216 224]
 [ 52  28  72  80 124 168 212 220   8]
 [ 24  68  76 120 164 208 252   4  48]
 [ 64 108 116 160 204 248   0  44  20]
 [104 112 156 200 244  32  40  16  60]
 [144 152 196 240  28  36  12  56 100]
 [148 192 236  24  68   8  52  96 140]]
